package ta.te.ti;

import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Ventana extends javax.swing.JFrame {
    
    JButton botones[][];
    Tablero tablero;
    Marca marca;
    JugadorVirtual jugadorVirtual;
    
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        botones = new JButton[3][3];
        
        botones[0][0] = btn00;
        botones[0][1] = btn01;
        botones[0][2] = btn02;
        botones[1][0] = btn10;
        botones[1][1] = btn11;
        botones[1][2] = btn12;
        botones[2][0] = btn20;
        botones[2][1] = btn21;
        botones[2][2] = btn22;
        
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                botones[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent me) {
                        botonesClick(me);
                    }
                    
                });
            }
        }
        inicializarJuego();
    }
    
    private void botonesClick(java.awt.event.MouseEvent evt) {
        JButton btn = ((JButton) evt.getSource());
        if (!btn.isEnabled() || partidaTerminada()) {
            return;
        }
        
        // parte del jugador humano...
        btn.setEnabled(false);
        int x = Integer.valueOf("" + btn.getName().charAt(0));
        int y = Integer.valueOf("" + btn.getName().charAt(1));
        tablero.set(x, y, marca);
        actualizarTablero(tablero);
        if (partidaTerminada()){
            inicializarJuego();
            return;
        }
        
        // parte del jugador virtual
        String s = jugadorVirtual.jugarTurno(tablero);
        x = Integer.valueOf("" + s.charAt(0));
        y = Integer.valueOf("" + s.charAt(1));
        botones[x][y].setEnabled(false);
        actualizarTablero(tablero);
        if (partidaTerminada()){
            inicializarJuego();
            return;
        }
    }
    
    private boolean partidaTerminada(){
        boolean ret = true;
        // 
        if (tablero.getGanador() == Marca.VACIO){
            if (tablero.estaLleno()){
                // Empate
                JOptionPane.showMessageDialog(this, "¡Empate!", "Partida terminada", JOptionPane.WARNING_MESSAGE);
            }else{
               // el juego sigue
                ret = false;
            }
        }else if (tablero.getGanador() == marca){
            // humano gana
            JOptionPane.showMessageDialog(this, "¡Ganaste!", "Partida terminada", JOptionPane.WARNING_MESSAGE);
        }else {
            // humano pierde
            JOptionPane.showMessageDialog(this, "¡Perdiste!", "Partida terminada", JOptionPane.WARNING_MESSAGE);
        }
        return ret;
    }
    
    private void inicializarJuego(){
        pnlBotones.setEnabled(false);
        tablero = new Tablero();
        marca = Marca.X;
        jugadorVirtual = new JugadorVirtual(marca.getOpuesta(), false);
        actualizarTablero(tablero);
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                botones[i][j].setEnabled(true);
            }
        }
        pnlBotones.setEnabled(true);
    }
    
    private void actualizarTablero(Tablero t){
        Casilla tab[][] = t.getTablero();
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                String s = tab[i][j].getMarca().toString();
                botones[i][j].setText(s);
            }
        }
    }
    
    
    ////////////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btn01 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn00 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ta-Te-Ti");
        setResizable(false);

        pnlBotones.setBackground(new java.awt.Color(0, 0, 0));

        btn01.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn01.setText("O");
        btn01.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn01.setMinimumSize(new java.awt.Dimension(100, 100));
        btn01.setName("01"); // NOI18N
        btn01.setPreferredSize(new java.awt.Dimension(100, 100));

        btn11.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn11.setText("X");
        btn11.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn11.setMinimumSize(new java.awt.Dimension(100, 100));
        btn11.setName("11"); // NOI18N
        btn11.setPreferredSize(new java.awt.Dimension(100, 100));

        btn00.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn00.setText("X");
        btn00.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn00.setMinimumSize(new java.awt.Dimension(100, 100));
        btn00.setName("00"); // NOI18N
        btn00.setPreferredSize(new java.awt.Dimension(100, 100));

        btn02.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn02.setText("X");
        btn02.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn02.setMinimumSize(new java.awt.Dimension(100, 100));
        btn02.setName("02"); // NOI18N
        btn02.setPreferredSize(new java.awt.Dimension(100, 100));

        btn10.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn10.setText("O");
        btn10.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn10.setMinimumSize(new java.awt.Dimension(100, 100));
        btn10.setName("10"); // NOI18N
        btn10.setPreferredSize(new java.awt.Dimension(100, 100));

        btn12.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn12.setText("O");
        btn12.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn12.setMinimumSize(new java.awt.Dimension(100, 100));
        btn12.setName("12"); // NOI18N
        btn12.setPreferredSize(new java.awt.Dimension(100, 100));

        btn20.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn20.setText("X");
        btn20.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn20.setMinimumSize(new java.awt.Dimension(100, 100));
        btn20.setName("20"); // NOI18N
        btn20.setPreferredSize(new java.awt.Dimension(100, 100));

        btn21.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn21.setText("O");
        btn21.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn21.setMinimumSize(new java.awt.Dimension(100, 100));
        btn21.setName("21"); // NOI18N
        btn21.setPreferredSize(new java.awt.Dimension(100, 100));

        btn22.setFont(new java.awt.Font("Franklin Gothic Book", 1, 60)); // NOI18N
        btn22.setText("X");
        btn22.setMaximumSize(new java.awt.Dimension(1000, 1000));
        btn22.setMinimumSize(new java.awt.Dimension(100, 100));
        btn22.setName("22"); // NOI18N
        btn22.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBotonesLayout.createSequentialGroup()
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn00, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JPanel pnlBotones;
    // End of variables declaration//GEN-END:variables
}
